apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 50053
      targetPort: http-auth
      name: http-auth-service
  type: ClusterIP
