apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: auth-db
data:
  POSTGRES_DB: authdb
  POSTGRES_USER: authuser
  postgres.conf: |
    max_connections = 100
    shared_buffers = 128MB
    effective_cache_size = 512MB
    maintenance_work_mem = 64MB
    checkpoint_completion_target = 0.9
    wal_buffers = 4MB
    default_statistics_target = 100
    random_page_cost = 1.1
    effective_io_concurrency = 200
    work_mem = 4MB
    min_wal_size = 1GB
    max_wal_size = 4GB
