# 03-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: auth-db
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM= # 'password123' encoded
  POSTGRES_ROOT_PASSWORD: YWRtaW5wYXNzd29yZA== # 'adminpassword' encoded
