apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: auth-db
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.3
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: postgres-config-volume
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgres.conf
          resources:
            requests:
              memory: '256Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          readinessProbe:
            exec:
              command: ['pg_isready', '-U', 'authuser', '-d', 'authdb']
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ['pg_isready', '-U', 'authuser', '-d', 'authdb']
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: postgres-storage
        resources:
          requests:
            storage: 1Gi
