apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuname: StandardSSD_LRS
  kind: managed
allowVolumeExpansion: true
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: postgres-storage
#   namespace: auth-db
# provisioner: k8s.io/minikube-hostpath # For minikube - will change for Azure
# reclaimPolicy: Retain
# volumeBindingMode: Immediate
